import { NextRequest, NextResponse } from 'next/server'
import { query } from '@/lib/db'
import { resolveClientId } from '@/lib/client-context'
import { SOVEREIGN_CLIENT_GENERATION_TARGET } from '@/lib/outbound-copy'

const HUMAN_MATCHED_REPLY_SQL = `
  COALESCE(metadata->>'matched_to_outbound', 'false') = 'true'
  AND COALESCE(metadata->>'is_auto_response', 'false') <> 'true'
  AND NOT (
    LOWER(
      COALESCE(metadata->>'subject', '') || ' ' ||
      COALESCE(metadata->>'body', '') || ' ' ||
      COALESCE(metadata->>'body_text', '')
    ) LIKE ANY (ARRAY[
      '%auto-generated email%',
      '%autogenerated email%',
      '%automated email%',
      '%automatic reply%',
      '%out of office%',
      '%ticket no%',
      '%ticket number%',
      '%thanks for writing to us%',
      '%we will get back to you within%',
      '%do not reply%'
    ])
  )
`

const HUMAN_MATCHED_REPLY_EVENT_SQL = HUMAN_MATCHED_REPLY_SQL.replaceAll('metadata', 'e.metadata')

export async function GET(request: NextRequest) {
  try {
    const clientId = await resolveClientId({ headers: request.headers })
    const limit = Math.max(1, Math.min(Number(request.nextUrl.searchParams.get('limit') ?? 100), 500))
    const summaryOnly = ['1', 'true', 'yes'].includes(
      String(request.nextUrl.searchParams.get('summaryOnly') ?? '').toLowerCase()
    )

    const [eventsRes, statsRes] = await Promise.all([
      // Main event feed
      summaryOnly
        ? Promise.resolve({ rows: [], rowCount: 0 })
        : query<{
            id: number
            event_type: string
            created_at: string
            campaign_id: number | null
            campaign_name: string | null
            queue_job_id: number | null
            provider_message_id: string | null
            to_email: string | null
            from_email: string | null
            subject: string | null
            error: string | null
            body_text: string | null
            body_html: string | null
            provider: string | null
            offer_type: string | null
          }>(
            `SELECT
               e.id,
               e.event_type,
               e.created_at::text AS created_at,
               NULL::bigint AS campaign_id,
               NULL::text AS campaign_name,
               NULL::bigint AS queue_job_id,
               NULL::text AS provider_message_id,
               CASE
                 WHEN e.event_type = 'reply' THEN COALESCE(NULLIF(e.metadata->>'from_email',''), NULLIF(e.metadata->>'from',''), c.email)
                 ELSE COALESCE(NULLIF(e.metadata->>'to_email',''), NULLIF(e.metadata->>'to',''), NULLIF(e.metadata->>'recipient',''), c.email)
               END AS to_email,
               CASE
                 WHEN e.event_type = 'reply' THEN COALESCE(NULLIF(e.metadata->>'to_email',''), NULLIF(e.metadata->>'to',''))
                 ELSE COALESCE(NULLIF(e.metadata->>'from_email',''), NULLIF(e.metadata->>'from',''))
               END AS from_email,
               COALESCE(NULLIF(e.metadata->>'subject',''), NULLIF(e.metadata->>'email_subject','')) AS subject,
               COALESCE(NULLIF(e.metadata->>'error',''), NULLIF(e.metadata->>'reason','')) AS error,
               COALESCE(NULLIF(e.metadata->>'body_text',''), NULLIF(e.metadata->>'body','')) AS body_text,
               e.metadata->>'body_html' AS body_html,
               COALESCE(NULLIF(e.metadata->>'provider',''), NULLIF(e.metadata->>'sending_provider','')) AS provider,
               NULLIF(e.metadata->>'offer_type','') AS offer_type
             FROM events e
             LEFT JOIN contacts c ON c.id = e.contact_id AND c.client_id = e.client_id
             WHERE e.client_id = $1
               AND (
                 e.event_type IN ('sent','failed','bounce')
                 OR (
                   e.event_type = 'reply'
                   AND ${HUMAN_MATCHED_REPLY_EVENT_SQL}
                 )
               )
             ORDER BY e.created_at DESC
             LIMIT $2`,
            [clientId, limit]
          ),

      // Summary stats: sent/failed/bounce + reply counts + follow-up + provider breakdown
      query<{
        sent_today: string
        sent_24h: string
        failed_24h: string
        bounced_24h: string
        replies_24h: string
        sent_7d: string
        replies_7d: string
        agency_sent_24h: string
        direct_sent_24h: string
        top_failure_reason: string | null
        top_provider: string | null
      }>(
        `SELECT
           COUNT(*) FILTER (WHERE event_type = 'sent' AND created_at >= CURRENT_DATE)::text AS sent_today,
           COUNT(*) FILTER (WHERE event_type = 'sent' AND created_at >= NOW() - INTERVAL '24h')::text AS sent_24h,
           COUNT(*) FILTER (WHERE event_type = 'failed' AND created_at >= NOW() - INTERVAL '24h')::text AS failed_24h,
           COUNT(*) FILTER (WHERE event_type = 'bounce' AND created_at >= NOW() - INTERVAL '24h')::text AS bounced_24h,
           COUNT(*) FILTER (
             WHERE event_type = 'reply'
               AND created_at >= NOW() - INTERVAL '24h'
               AND ${HUMAN_MATCHED_REPLY_SQL}
           )::text AS replies_24h,
           COUNT(*) FILTER (WHERE event_type = 'sent' AND created_at >= NOW() - INTERVAL '7 days')::text AS sent_7d,
           COUNT(*) FILTER (
             WHERE event_type = 'reply'
               AND created_at >= NOW() - INTERVAL '7 days'
               AND ${HUMAN_MATCHED_REPLY_SQL}
           )::text AS replies_7d,
           COUNT(*) FILTER (
             WHERE event_type = 'sent'
               AND created_at >= NOW() - INTERVAL '24h'
               AND COALESCE(metadata->>'offer_type','') = 'agency'
           )::text AS agency_sent_24h,
           COUNT(*) FILTER (
             WHERE event_type = 'sent'
               AND created_at >= NOW() - INTERVAL '24h'
               AND COALESCE(metadata->>'offer_type','direct') <> 'agency'
           )::text AS direct_sent_24h,
           (
             SELECT COALESCE(NULLIF(metadata->>'error',''), NULLIF(metadata->>'reason',''))
             FROM events e2
             WHERE e2.client_id = $1
               AND e2.event_type IN ('failed','bounce')
               AND e2.created_at >= NOW() - INTERVAL '24h'
               AND COALESCE(NULLIF(e2.metadata->>'error',''), NULLIF(e2.metadata->>'reason','')) IS NOT NULL
             GROUP BY 1
             ORDER BY COUNT(*) DESC
             LIMIT 1
           ) AS top_failure_reason,
           (
             SELECT COALESCE(NULLIF(metadata->>'provider',''), NULLIF(metadata->>'sending_provider',''))
             FROM events e3
             WHERE e3.client_id = $1
               AND e3.event_type = 'sent'
               AND e3.created_at >= NOW() - INTERVAL '24h'
               AND COALESCE(NULLIF(e3.metadata->>'provider',''), NULLIF(e3.metadata->>'sending_provider','')) IS NOT NULL
             GROUP BY 1
             ORDER BY COUNT(*) DESC
             LIMIT 1
           ) AS top_provider
         FROM events
         WHERE client_id = $1
           AND created_at >= NOW() - INTERVAL '7 days'`,
        [clientId]
      ),
    ])

    const s = statsRes.rows[0]
    const sent24h = Number(s?.sent_24h ?? 0)
    const replies24h = Number(s?.replies_24h ?? 0)
    const sent7d = Number(s?.sent_7d ?? 0)
    const replies7d = Number(s?.replies_7d ?? 0)
    const failed24h = Number(s?.failed_24h ?? 0)
    const bounced24h = Number(s?.bounced_24h ?? 0)
    const deliveryAttempts24h = sent24h + failed24h + bounced24h
    const deliveryConfidence24h =
      deliveryAttempts24h > 0
        ? Math.max(0, Math.round(((deliveryAttempts24h - failed24h - bounced24h) / deliveryAttempts24h) * 1000) / 10)
        : 100

    const summary = {
      sentToday: Number(s?.sent_today ?? 0),
      sent24h,
      failed24h,
      bounced24h,
      replies24h,
      replyRate24h: sent24h > 0 ? Math.round((replies24h / sent24h) * 1000) / 10 : 0,
      replyTargetPct: 100,
      clientConversationTargetMin:
        SOVEREIGN_CLIENT_GENERATION_TARGET.dailyQualifiedConversationsMin,
      clientConversationTargetMax:
        SOVEREIGN_CLIENT_GENERATION_TARGET.dailyQualifiedConversationsMax,
      operatingSendFloor: SOVEREIGN_CLIENT_GENERATION_TARGET.operatingSendFloor,
      operatingSendCeiling: SOVEREIGN_CLIENT_GENERATION_TARGET.operatingSendCeiling,
      clientGenerationStatus:
        replies24h >= SOVEREIGN_CLIENT_GENERATION_TARGET.dailyQualifiedConversationsMin
          ? 'on_track'
          : Number(s?.sent_today ?? 0) >= SOVEREIGN_CLIENT_GENERATION_TARGET.operatingSendFloor
            ? 'tighten_targeting'
            : 'building_inventory',
      deliveryConfidence24h,
      sent7d,
      replies7d,
      replyRate7d: sent7d > 0 ? Math.round((replies7d / sent7d) * 1000) / 10 : 0,
      agencySent24h: Number(s?.agency_sent_24h ?? 0),
      directSent24h: Number(s?.direct_sent_24h ?? 0),
      topFailureReason: s?.top_failure_reason ?? null,
      topProvider: s?.top_provider ?? null,
    }

    return NextResponse.json({
      ok: true,
      summary,
      items: eventsRes.rows.map((r) => ({
        id: Number(r.id),
        type: r.event_type,
        createdAt: r.created_at,
        campaignId: r.campaign_id ? Number(r.campaign_id) : null,
        campaignName: r.campaign_name ?? null,
        queueJobId: r.queue_job_id ? Number(r.queue_job_id) : null,
        providerMessageId: r.provider_message_id ?? null,
        toEmail: r.to_email ?? '',
        fromEmail: r.from_email ?? '',
        subject: r.subject ?? '',
        error: r.error ?? null,
        bodyText: r.body_text ?? '',
        bodyHtml: r.body_html ?? '',
        provider: r.provider ?? null,
        offerType: r.offer_type ?? null,
      })),
    })
  } catch (error) {
    console.error('[api/dashboard/sent] failed', error)
    return NextResponse.json({ ok: false, error: 'failed' }, { status: 500 })
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const clientId = await resolveClientId({ headers: request.headers })
    const kind = String(request.nextUrl.searchParams.get('kind') ?? 'failed').trim().toLowerCase()

    if (kind === 'failed') {
      await query(
        `DELETE FROM events
         WHERE client_id = $1
           AND event_type IN ('failed','bounce')`,
        [clientId]
      )
      return NextResponse.json({ ok: true })
    }

    if (kind === 'test') {
      // Clear test runs based on the stable subject prefix used by send:test.
      await query(
        `DELETE FROM events
         WHERE client_id = $1
           AND event_type IN ('sent','failed','bounce')
           AND COALESCE(metadata->>'subject','') LIKE '[Sovereign Engine Test]%'`,
        [clientId]
      )
      return NextResponse.json({ ok: true })
    }

    return NextResponse.json({ ok: false, error: 'invalid_kind' }, { status: 400 })
  } catch (error) {
    console.error('[api/dashboard/sent] delete failed', error)
    return NextResponse.json({ ok: false, error: 'failed' }, { status: 500 })
  }
}
